import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Import your AuthProvider - update the path if yours is different!
import { AuthProvider } from "@/context/AuthContext"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // Added suppressHydrationWarning to the html tag
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        // Added suppressHydrationWarning to the body tag to stop the Grammarly error
        suppressHydrationWarning
      >
        {/* Wrap children in AuthProvider so useAuth() works 
            in your SettingsPage and Navbar 
        */}
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}